//! Randomised invariant tests for `ClockTtlCache`.
//!
//! Where the unit tests in `src/lib.rs` pin specific scenarios and the
//! loom tests in `tests/loom_invariants.rs` enumerate concurrent
//! interleavings, this file uses [`proptest`] to generate large
//! sequences of randomised operations and verify that the cache's
//! observable invariants hold across all of them.
//!
//! Failure mode of choice: when a property fails, proptest's shrinker
//! finds a minimal counterexample; usually a 2–3 op sequence that
//! reproduces the bug, which beats hand-debugging a 200-op trace.
//!
//! # Properties pinned here
//!
//! 1. **Capacity bound**: `cache.len() <= capacity` after any sequence
//!    of inserts, gets, invalidates, and clock advances.
//! 2. **TTL boundary**: a single insert + advance + get returns
//!    `Some(v)` iff the advance stayed within the TTL window.
//! 3. **Invalidate idempotence**: a second `invalidate(k)` doesn't
//!    change `len()` or the result of `get(k)`.
//! 4. **Insert overwrite**: when a key is inserted multiple times,
//!    `get(k)` returns the value from the *last* insert.
//!
//! # Out of scope
//!
//! - **LRU recency**: well-covered by deterministic unit tests; a
//!   proptest version would require maintaining a parallel reference
//!   model and a public iteration API the cache doesn't expose.
//! - **Concurrent invariants**: covered by `loom_invariants.rs`;
//!   proptest doesn't model thread interleavings.

use axess_cache::ClockTtlCache;
use axess_clock::Clock;
use axess_clock::testing::MockClock;
use chrono::{TimeZone, Utc};
use proptest::prelude::*;
use std::num::NonZeroUsize;
use std::sync::Arc;
use std::time::Duration;

/// One randomised operation against the cache. Generated by
/// [`op_strategy`] and applied via [`apply_op`].
///
/// `Advance` carries an `i64` because `MockClock::advance_secs` takes
/// `i64` (chrono's native unit); proptest's bounded ranges keep us
/// well clear of overflow.
#[derive(Debug, Clone)]
enum Op {
    Insert(u32, u32),
    Get(u32),
    Invalidate(u32),
    Advance(i64),
}

fn op_strategy() -> impl Strategy<Value = Op> {
    // Constrain key space to a small range (0..16) so different ops in
    // a sequence have a meaningful chance of touching the same key;
    // otherwise every op would address a unique key and we'd never
    // exercise the overwrite/invalidate/cache-pressure paths.
    prop_oneof![
        (0u32..16, any::<u32>()).prop_map(|(k, v)| Op::Insert(k, v)),
        (0u32..16).prop_map(Op::Get),
        (0u32..16).prop_map(Op::Invalidate),
        (1i64..=120).prop_map(Op::Advance),
    ]
}

fn build_cache(capacity: usize, ttl_secs: u64) -> (ClockTtlCache<u32, u32>, Arc<MockClock>) {
    let clock = Arc::new(MockClock::at(
        Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap(),
    ));
    let cache = ClockTtlCache::new(
        NonZeroUsize::new(capacity).unwrap(),
        Duration::from_secs(ttl_secs),
        clock.clone() as Arc<dyn Clock>,
    );
    (cache, clock)
}

fn apply_op(cache: &ClockTtlCache<u32, u32>, clock: &MockClock, op: Op) {
    match op {
        Op::Insert(k, v) => cache.insert(k, v),
        Op::Get(k) => {
            let _ = cache.get(&k);
        }
        Op::Invalidate(k) => {
            cache.invalidate(&k);
        }
        Op::Advance(secs) => clock.advance_secs(secs),
    }
}

proptest! {
    /// Property 1: cache size is bounded by the configured capacity
    /// after every operation, regardless of sequence. The bound comes
    /// from `LruCache::put`'s contract; randomising the op stream
    /// pins it against accidental violations introduced by future
    /// changes.
    #[test]
    fn cache_size_never_exceeds_capacity(
        capacity in 1usize..=32,
        ops in proptest::collection::vec(op_strategy(), 0..=200),
    ) {
        let (cache, clock) = build_cache(capacity, 60);
        for op in ops {
            apply_op(&cache, &clock, op);
            prop_assert!(
                cache.len() <= capacity,
                "len={} exceeded capacity={}",
                cache.len(),
                capacity,
            );
        }
    }

    /// Property 2: for any TTL and any advance, a get of a freshly
    /// inserted key returns Some iff the advance stayed within TTL.
    /// Pins the boundary semantic across the full Cartesian space of
    /// (TTL, advance); easy to write, easy to break with off-by-one.
    ///
    /// Boundary is `>=`: at exactly `expires_at_micros == now_micros`,
    /// the entry is still present (matches the implementation).
    #[test]
    fn ttl_boundary_get_within_returns_some_after_returns_none(
        capacity in 4usize..=32,
        ttl_secs in 10u64..=300,
        v in any::<u32>(),
        // i64 because `MockClock::advance_secs` takes i64; bounded
        // range keeps us comfortably below overflow.
        advance_secs in 0i64..=600,
    ) {
        let (cache, clock) = build_cache(capacity, ttl_secs);
        cache.insert(42u32, v);
        clock.advance_secs(advance_secs);
        let result = cache.get(&42);
        // Compare in i64; both sides fit since ttl_secs <= 300.
        if advance_secs <= ttl_secs as i64 {
            prop_assert_eq!(
                result, Some(v),
                "advance={}, ttl={}; within TTL boundary, expected Some({})",
                advance_secs, ttl_secs, v,
            );
        } else {
            prop_assert_eq!(
                result, None,
                "advance={}, ttl={}; past TTL boundary, expected None",
                advance_secs, ttl_secs,
            );
        }
    }

    /// Property 3: a second invalidate of the same key changes nothing
    /// further (idempotence). Pins the no-op behaviour of the second
    /// call against accidental introduction of side effects (e.g.
    /// double-counting in the invalidations counter, decrementing
    /// len(), etc.).
    #[test]
    fn invalidate_is_idempotent(
        capacity in 4usize..=32,
        kvs in proptest::collection::vec((0u32..16, any::<u32>()), 1..=20),
        target in 0u32..16,
    ) {
        let (cache, _clock) = build_cache(capacity, 60);
        for (k, v) in &kvs {
            cache.insert(*k, *v);
        }
        cache.invalidate(&target);
        let len_after_first = cache.len();
        cache.invalidate(&target);
        prop_assert_eq!(
            cache.len(), len_after_first,
            "second invalidate must not change len",
        );
        prop_assert_eq!(
            cache.get(&target), None,
            "after invalidate, get(target) must be None",
        );
    }

    /// Property 4: when a key is inserted multiple times, `get`
    /// returns the value from the most recent insert. Pins
    /// "last write wins" semantics across arbitrary insert sequences.
    #[test]
    fn insert_overwrite_returns_latest_value(
        capacity in 4usize..=32,
        values in proptest::collection::vec(any::<u32>(), 1..=20),
    ) {
        let (cache, _clock) = build_cache(capacity, 60);
        let key = 42u32;
        let mut last_value = None;
        for v in &values {
            cache.insert(key, *v);
            last_value = Some(*v);
        }
        prop_assert_eq!(
            cache.get(&key), last_value,
            "get must return the most recently inserted value",
        );
    }
}
