/// Middleware for generating and setting a request ID in the headers of incoming requests.
/// The request ID is generated by a `RequestIdGenerator` and set in the headers of the request.
/// The request ID is then passed to the inner service and can be retrieved from the request
/// extensions. With the `accept_client_id" feature activated, requests that already contains a
/// valid request ID will not be overwritten, but requests with invalid request IDs will be.
/// When the feature is not activated, the request ID will always be overwritten.
///
/// The `RequestIdLayer` is a `tower::Layer` that can be used to wrap a service with the
/// `RequestIdService`. The `RequestIdService` will generate a request ID if none is provided and
/// set it in the request headers. The `RequestIdService` will also ensure that the request ID is
/// set in the response headers. The request ID can be retrieved from the request extensions using
/// the `RequestIdExt` trait. As the `RequestIdService` is a `tower::Service` itself, it can be
/// used with other services that implement the `tower::Service` trait; it can be used with any
/// service that takes a `Request<Body>` and returns a `Response<Body>`.
///
/// The `RequestIdGenerator` trait is used to define the behavior of the request ID generator.
/// The `UuidGenerator` is a default implementation that generates a UUID v4 request ID. To use a
/// custom request ID generator, implement the `RequestIdGenerator` trait and pass it to the
/// `RequestIdLayer` when wrapping the service. To use a custom header name for the request ID,
/// implement the `RequestIdGenerator` trait and set the `HEADER_NAME` constant to the desired
/// header name. Please note that the HEADER_NAME must be in lowercase as per HTTP/2 and HTTP/3
/// specification. The ID_LENGTH constant relates to the HeaderValue and can be used to specify
/// the length of the request ID, which is used as a basic validation of the client-provided IDs
/// when the `accept_client_id` feature is activated.
///
/// The simplest way to add a request ID to all your requests, is to simply apply the default layer
/// to your service as `.layer(RequestIdLayer::default())`. This will generate a UUID v4 request ID
/// for each incoming request and then propagate this ID to the inner service and the response.
///
use axum::{
    body::Body,
    extract::Request,
    http::header::{HeaderName, HeaderValue},
    response::Response,
};
// use http::header::{HeaderName, HeaderValue};
use std::{
    future::Future,
    io::Error as IoError,
    pin::Pin,
    sync::Arc,
    task::{Context, Poll},
};
use tower::{Layer, Service};
use uuid::Uuid;

const X_REQUEST_ID: HeaderName = HeaderName::from_static("x-request-id");

#[derive(Clone)]
struct RequestId(String);

pub trait RequestIdGenerator {
    const HEADER_NAME: HeaderName;

    #[cfg(feature = "accept_client_id")]
    const ID_LENGTH: usize;

    fn generate(&self) -> HeaderValue;
}

#[derive(Clone, Debug)]
pub struct UuidGenerator;

impl RequestIdGenerator for UuidGenerator {
    const HEADER_NAME: HeaderName = X_REQUEST_ID;

    #[cfg(feature = "accept_client_id")]
    const ID_LENGTH: usize = 36;

    fn generate(&self) -> HeaderValue {
        HeaderValue::from_str(&Uuid::new_v4().to_string()).expect("Invalid header value")
    }
}

impl Default for UuidGenerator {
    fn default() -> Self {
        Self
    }
}

// The RequestIdService will generate and set the request ID in the headers
#[derive(Clone, Debug)]
pub struct RequestIdService<S, G> {
    inner: S,
    generator: Arc<G>,
}

impl<S, G> RequestIdService<S, G>
where
    S: Clone,
    G: RequestIdGenerator + Clone,
{
    pub fn new(inner: S, generator: G) -> Self {
        Self {
            inner,
            generator: generator.into(),
        }
    }

    /// Helper function to ensure that a request ID is set in the request headers.
    fn ensure_request_id(&self, req: &mut Request<Body>) -> Result<HeaderValue, IoError> {
        #[cfg(feature = "accept_client_id")]
        if let Some(existing_id) = req.headers().get(&G::HEADER_NAME) {
            let existing_id = existing_id.clone();
            if let Ok(id) = existing_id.to_str() {
                if id.len() == G::ID_LENGTH {
                    // If the client sent a valid request ID, do nothing with message header.
                    if let Some(request_id) = req.extensions().get::<RequestId>() {
                        if request_id.0 != *id {
                            req.extensions_mut()
                                // .insert(RequestId(id.to_string()));
                                .insert(existing_id.clone());
                        }
                    } else {
                        req.extensions_mut().insert(RequestId(id.to_string()));
                    }
                    return Ok(existing_id);
                }
            }
        }

        let request_id = self.generator.generate();
        req.headers_mut()
            .insert(&G::HEADER_NAME, request_id.clone());
        req.extensions_mut()
            .insert(RequestId(request_id.to_str().unwrap().to_string()));

        Ok(request_id)
    }
}

impl<S, G> Service<Request<Body>> for RequestIdService<S, G>
where
    S: Service<Request<Body>, Response = Response<Body>> + Send + Clone + 'static,
    S::Future: Send + 'static,
    S::Error: Into<Box<dyn std::error::Error + Send + Sync>>,
    G: RequestIdGenerator + Send + Sync + Clone + 'static,
{
    type Response = S::Response;
    type Error = S::Error;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.inner.poll_ready(cx)
    }

    fn call(&mut self, mut req: Request<Body>) -> Self::Future {
        let request_id = match self.ensure_request_id(&mut req) {
            Ok(id) => id,
            Err(_) => {
                // If we can't generate a request ID, we'll skip it and continue
                // This is more robust than failing the entire request
                tracing::warn!("Failed to generate request ID, continuing without it");
                HeaderValue::from_static("unknown")
            }
        };

        let fut = self.inner.call(req);
        Box::pin(async move {
            let mut res = fut.await?;
            if res.headers().get(G::HEADER_NAME).is_none() {
                res.headers_mut().insert(G::HEADER_NAME, request_id);
            }
            Ok(res)
        })
    }
}

#[derive(Clone, Debug)]
pub struct RequestIdLayer<G> {
    generator: G,
}

impl<G> RequestIdLayer<G>
where
    G: RequestIdGenerator,
{
    pub fn new(generator: G) -> Self {
        Self { generator }
    }
}

impl Default for RequestIdLayer<UuidGenerator> {
    fn default() -> Self {
        RequestIdLayer {
            generator: UuidGenerator,
        }
    }
}

impl<S, G> Layer<S> for RequestIdLayer<G>
where
    G: RequestIdGenerator + Clone,
{
    type Service = RequestIdService<S, G>;

    fn layer(&self, service: S) -> Self::Service {
        RequestIdService {
            inner: service,
            generator: Arc::new(self.generator.clone()),
        }
    }
}

/// Extension trait to easily retrieve the request ID from a request.
pub trait RequestIdExt {
    fn request_id(&self) -> Option<&str>;
}

impl RequestIdExt for Request<Body> {
    fn request_id(&self) -> Option<&str> {
        self.extensions().get::<RequestId>().map(|id| id.0.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use tower::ServiceExt;

    #[derive(Clone)]
    struct MockGenerator {
        counter: Arc<AtomicUsize>,
    }

    impl RequestIdGenerator for MockGenerator {
        const HEADER_NAME: HeaderName = X_REQUEST_ID;

        #[cfg(feature = "accept_client_id")]
        const ID_LENGTH: usize = 8;

        fn generate(&self) -> HeaderValue {
            let id = self.counter.fetch_add(1, Ordering::SeqCst);
            let id_str = format!("{:04}", id % 10000); // Ensures 4 digits, rolls over at 9999; enough for testing.
            let mock_id = format!("mock{}", id_str);
            HeaderValue::from_str(&mock_id).expect("Invalid header value")
        }
    }

    impl Default for MockGenerator {
        fn default() -> Self {
            Self {
                counter: Arc::new(AtomicUsize::new(0)),
            }
        }
    }

    #[derive(Clone)]
    struct CustomHeaderGenerator;

    impl RequestIdGenerator for CustomHeaderGenerator {
        const HEADER_NAME: HeaderName = HeaderName::from_static("x-custom-id");

        #[cfg(feature = "accept_client_id")]
        const ID_LENGTH: usize = 12;

        fn generate(&self) -> HeaderValue {
            HeaderValue::from_str("custom-value").unwrap()
        }
    }

    impl Default for CustomHeaderGenerator {
        fn default() -> Self {
            Self
        }
    }

    #[derive(Clone)]
    struct MockService;

    impl Service<Request<Body>> for MockService {
        type Response = Response<Body>;
        type Error = std::io::Error;
        type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

        fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }

        fn call(&mut self, _req: Request<Body>) -> Self::Future {
            // let request_id = req.headers().get(X_REQUEST_ID).cloned();
            Box::pin(async move {
                // Echo back the request ID in the response
                // let mut res = Response::new(Body::empty());
                // if let Some(id) = request_id {
                //     res.headers_mut().insert(X_REQUEST_ID, id);
                // }
                // Ok(res)
                Ok(Response::new(Body::empty()))
            })
        }
    }

    fn create_service() -> RequestIdService<MockService, MockGenerator> {
        RequestIdService::new(MockService, MockGenerator::default())
    }

    #[tokio::test]
    /// Verifies that a request ID is generated when none is provided.
    async fn test_request_id_generation() {
        let service = create_service();
        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert!(id.starts_with("mock"));
        assert_eq!(id.len(), 8);
    }

    #[tokio::test]
    /// Ensures that a request ID is added to the response even if the inner service doesn't set one.
    async fn test_missing_request_id_in_response() {
        let service = create_service();
        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        assert!(res.headers().contains_key(X_REQUEST_ID));
    }

    #[tokio::test]
    /// Verifies that the service works correctly for multiple sequential requests, ensuring that
    /// the generated IDs are unique.
    async fn test_multiple_requests() {
        let service = create_service();
        let mut ids = Vec::new();
        for _ in 0..5 {
            let req = Request::new(Body::empty());
            let res = ServiceExt::oneshot(service.clone(), req).await.unwrap();
            let id = res
                .headers()
                .get(X_REQUEST_ID)
                .unwrap()
                .to_str()
                .unwrap()
                .to_string();
            assert!(!ids.contains(&id));
            ids.push(id);
        }
    }

    #[cfg_attr(feature = "accept_client_id", tokio::test)]
    #[cfg(feature = "accept_client_id")]
    /// Feature gated check that a valid client-provided ID is accepted and preserved.
    async fn test_accept_valid_client_id() {
        let service = create_service();
        let mut req = Request::new(Body::empty());
        req.headers_mut()
            .insert(X_REQUEST_ID, HeaderValue::from_static("12345678"));
        let res = ServiceExt::oneshot(service, req).await.unwrap();
        assert_eq!(res.headers().get(X_REQUEST_ID).unwrap(), "12345678");
    }

    #[cfg_attr(feature = "accept_client_id", tokio::test)]
    #[cfg(feature = "accept_client_id")]
    /// Feature gated check to ensures that an invalid client-provided ID is rejected and replaced.
    async fn test_reject_invalid_client_id() {
        let service = create_service();
        let mut req = Request::new(Body::empty());
        req.headers_mut()
            .insert(X_REQUEST_ID, HeaderValue::from_static("invalid")); // Length 7, but invalid format
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert!(id.starts_with("mock"));
        assert_eq!(id.len(), 8);
    }

    #[cfg_attr(feature = "accept_client_id", tokio::test)]
    #[cfg(feature = "accept_client_id")]
    /// Feature gated with the `accept_client_id` feature. The service should generate its own ID
    /// if the provided header value is badly formatted. This test ensures that the service
    /// correctly rejects a client-provided ID that is too short.
    async fn test_erroneous_id_length() {
        #[derive(Clone)]
        struct ErrorLengthGenerator;

        impl RequestIdGenerator for ErrorLengthGenerator {
            const HEADER_NAME: HeaderName = X_REQUEST_ID;
            const ID_LENGTH: usize = 5; // This is incorrect, should be 7

            fn generate(&self) -> HeaderValue {
                HeaderValue::from_str("12345").unwrap()
            }
        }

        let service = RequestIdService::new(MockService, ErrorLengthGenerator);
        let mut req = Request::new(Body::empty());
        req.headers_mut()
            .insert(X_REQUEST_ID, HeaderValue::from_static("1234567"));
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        // The service should reject the client ID and use its own, even though it's the wrong length
        assert_eq!(res.headers().get(X_REQUEST_ID).unwrap(), "12345");
    }

    #[tokio::test]
    #[cfg(not(feature = "accept_client_id"))]
    /// Verifies that the service correctly overwrites an existing request ID if
    /// the `accept_client_id` feature is disabled.
    async fn test_request_id_overwrite() {
        let service = create_service();
        let mut req = Request::new(Body::empty());
        req.headers_mut()
            .insert(X_REQUEST_ID, HeaderValue::from_static("existing-id"));
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert_eq!(id, "mock0000");
    }

    #[tokio::test]
    /// Verifies that the request ID can be retrieved correctly from the request as a UUID when
    /// using the default provided UUID v4 request ID generator.
    async fn test_default_generator() {
        let service = RequestIdService::new(MockService, UuidGenerator);
        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert!(uuid::Uuid::parse_str(id).is_ok());
    }

    #[tokio::test]
    /// Verifies that the request ID can be retrieved correctly from the request also when
    /// using a custom header name.
    async fn test_custom_header_name() {
        let service = RequestIdService::new(MockService, CustomHeaderGenerator);
        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        assert_eq!(res.headers().get("x-custom-id").unwrap(), "custom-value");
    }

    #[tokio::test]
    /// Verifies that multiple layers can be added to the service.
    async fn test_multiple_layers() {
        let service = tower::ServiceBuilder::new()
            .layer(RequestIdLayer::default())
            .layer(RequestIdLayer::new(MockGenerator::default()))
            .layer(RequestIdLayer::new(CustomHeaderGenerator))
            .layer(RequestIdLayer::new(MockGenerator::default()))
            .layer(RequestIdLayer::default())
            .service(MockService);

        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        assert_eq!(res.headers().get("x-custom-id").unwrap(), "custom-value");

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert!(!id.starts_with("mock"));
        assert_eq!(id.len(), 36);
        assert!(uuid::Uuid::parse_str(id).is_ok());
    }

    #[tokio::test]
    #[cfg(not(feature = "accept_client_id"))]
    /// Verifies that multiple header layers can be added to the service. The second layer
    /// should overwrite the first layer when `accept_client_id` feature isn't activated.
    async fn test_duplicate_layers_overriden_without_accept_client_id() {
        let service = tower::ServiceBuilder::new()
            .layer(RequestIdLayer::new(MockGenerator {
                counter: Arc::new(AtomicUsize::new(2000)),
            }))
            .layer(RequestIdLayer::new(MockGenerator {
                counter: Arc::new(AtomicUsize::new(8888)),
            }))
            .service(MockService);

        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert_eq!(id, "mock8888");
    }

    #[cfg_attr(feature = "accept_client_id", tokio::test)]
    #[cfg(feature = "accept_client_id")]
    /// Verifies that multiple header layers can be added to the service. The second layer
    /// should NOT overwrite the first layer when `accept_client_id` feature is activated.
    async fn test_duplicate_layers_not_overriden_with_accept_client_id() {
        let service = tower::ServiceBuilder::new()
            .layer(RequestIdLayer::new(MockGenerator {
                counter: Arc::new(AtomicUsize::new(5555)),
            }))
            .layer(RequestIdLayer::new(MockGenerator {
                counter: Arc::new(AtomicUsize::new(1000)),
            }))
            .service(MockService);

        let req = Request::new(Body::empty());
        let res = ServiceExt::oneshot(service, req).await.unwrap();

        let id = res.headers().get(X_REQUEST_ID).unwrap().to_str().unwrap();
        assert_eq!(id, "mock5555");
    }
}
