[package]
name = "axess"
version = "0.0.14"
publish = false
edition = "2024"
resolver = "3"
description = """
Authentication and Authorization for the Axum webframework. Providing a set of convenient middleware and related request extractors.
Custom session layer with HMAC-signed cookies and Cedar Policy for authorization. Additionally including helpers for
request tracing and request id generation.
"""
authors = ["Gnomes <info@gnomes.ch>"]
license = "MIT"
repository = "https://github.com/GnomesOfZurich/axess"
keywords = ["authentication", "authorization", "axum", "login", "session", "tower", "cedar"]
categories = ["web-programming"]
exclude = ["/.github", "/examples", "/scripts"]

[dependencies]
axess-core = { path = "../axess-core" }
axess-macros = { path = "../axess-macros" }
axess-factors = { path = "../axess-factors" }
axum = { version = "0.8.8", default-features = false, features = ["json"] }
cedar-policy = { version = "4.9.1", optional = true }
serde_json = "1.0.149"
tower-layer = "0.3.3"
tower-service = "0.3.3"

[features]
authz = ["axess-core/authz", "dep:cedar-policy"]
request_id = ["axess-core/request_id"]
trace_id = ["axess-core/trace_id"]
accept_client_id = ["axess-core/accept_client_id"]
memory = []
sqlite = ["axess-core/sqlite"]
valkey = ["axess-core/valkey"]
fido2 = ["axess-core/fido2"]
oauth = ["axess-core/oauth"]
full = ["authz", "request_id", "trace_id", "sqlite", "valkey", "fido2", "oauth"]
default = ["authz"]

[dev-dependencies]
axum = { version = "0.8.8", features = ["macros"] }
tokio = { version = "1.50.0", features = ["full"] }
tower = { version = "0.5.3", features = ["util"] }
