use crate::{
    authn::{errors::FormError, methods::factor::AuthFactorKind},
    tracing::error,
};
use password_auth::verify_password;
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, fmt::Debug};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum FactorFormKind {
    Setup,
    Verify,
}

pub trait FactorForm: Send + Sync + Debug + for<'de> Deserialize<'de> {
    /// Which factor is this form for?
    fn factor_kind(&self) -> AuthFactorKind;
    /// Is this a setup or verification form?
    fn form_kind(&self) -> FactorFormKind;
    /// Validate the form before backend processing
    fn validate_form(&self) -> Result<&Self, FormError>;
    /// Get the authentication credential from the form, if applicable (password, TOTP code, OAuth provider, etc.)
    fn credential(&self) -> Option<&str>;
    /// Get the fields as a map for easier processing
    fn fields_map(&self) -> HashMap<String, String>;
    /// Verify credentials against the factor's stored configuration (e.g., password or TOTP secret)
    fn verify_against_config(&self, config: &serde_json::Value) -> Result<&Self, FormError>;
}

#[derive(Debug, Clone, Deserialize)]
pub struct PasswordForm {
    pub username: String,
    pub password: String,
    pub tenant: Option<String>,
    pub next: Option<String>,
}
impl FactorForm for PasswordForm {
    fn factor_kind(&self) -> AuthFactorKind {
        AuthFactorKind::Password
    }

    fn form_kind(&self) -> FactorFormKind {
        FactorFormKind::Verify
    }

    fn validate_form(&self) -> Result<&Self, FormError> {
        if self.username.is_empty()
            || self.username.len() > 64
            || self.password.len() < 8
            || self.password.len() > 512
        {
            Err(FormError::ValidationFailed(
                "Username must be between 1 and 64 characters, password must be between 8 and 512 characters.".to_string(),
            ))
        } else {
            Ok(self)
        }
    }

    fn credential(&self) -> Option<&str> {
        if self.password.is_empty() {
            None
        } else {
            Some(&self.password)
        }
    }

    fn fields_map(&self) -> HashMap<String, String> {
        let mut map = HashMap::new();
        map.insert("username".to_string(), self.username.clone());
        map.insert("password".to_string(), self.password.clone());
        if let Some(tenant) = &self.tenant {
            map.insert("tenant".to_string(), tenant.clone());
        }
        if let Some(next) = &self.next {
            map.insert("next".to_string(), next.clone());
        }
        map
    }

    fn verify_against_config(&self, config: &serde_json::Value) -> Result<&Self, FormError> {
        let credential = self.credential().ok_or_else(|| {
            FormError::ValidationFailed("Missing password credential.".to_string())
        })?;

        if let Some(stored_password) = config.get("password").and_then(|v| v.as_str()) {
            match verify_password(credential, stored_password) {
                Ok(()) => Ok(self),
                Err(_) => {
                    error!(
                        "Failed Password verification failed for {:?}",
                        self.username
                    );
                    Err(FormError::ValidationFailed(
                        "Invalid username or password.".to_string(),
                    ))
                }
            }
        } else {
            Err(FormError::AuthConfigError(
                AuthFactorKind::Password.to_string(),
            ))
        }
    }
}

/// Form for setting up a TOTP factor.
/// This is used when the user is registering a new TOTP factor.
/// It includes the TOTP secret and an optional redirect URL after setup.
/// The secret is typically generated by the server and displayed to the user.
/// The user will then use this secret to configure their TOTP app.
#[derive(Debug, Clone, Deserialize)]
pub struct TotpSetupForm {
    pub secret: String,
    pub tenant: Option<String>,
    pub next: Option<String>,
}

impl FactorForm for TotpSetupForm {
    fn factor_kind(&self) -> AuthFactorKind {
        AuthFactorKind::Totp
    }

    fn form_kind(&self) -> FactorFormKind {
        FactorFormKind::Setup
    }

    fn validate_form(&self) -> Result<&Self, FormError> {
        if self.secret.is_empty() {
            Err(FormError::ValidationFailed(
                "TOTP secret cannot be empty.".to_string(),
            ))
        } else if self.secret.len() < 4 {
            // TODO: Add more complex validation logic for TOTP secrets
            Err(FormError::ValidationFailed(
                "TOTP secret must be at least 4 characters long.".to_string(),
            ))
        } else {
            Ok(self)
        }
    }

    fn credential(&self) -> Option<&str> {
        Some(&self.secret)
    }

    fn fields_map(&self) -> HashMap<String, String> {
        let mut map = HashMap::new();
        map.insert("secret".to_string(), self.secret.clone());
        if let Some(tenant) = &self.tenant {
            map.insert("tenant".to_string(), tenant.clone());
        }
        if let Some(next) = &self.next {
            map.insert("next".to_string(), next.clone());
        }
        map
    }

    fn verify_against_config(&self, _config: &serde_json::Value) -> Result<&Self, FormError> {
        // For factor setup, verification against existing credentials is not meaningful.
        // Instead, just validate the form and allow setup to proceed.
        self.validate_form()
    }
}

/// Form for verifying a TOTP code.
/// This is used when the user is entering a TOTP code to complete authentication.
/// It includes the TOTP code and an optional redirect URL after verification.
/// The code is typically generated by the user's TOTP app and must match the expected value.
#[derive(Debug, Clone, Deserialize)]
pub struct TotpVerifyForm {
    pub code: String,
    pub tenant: Option<String>,
    pub next: Option<String>,
}

impl FactorForm for TotpVerifyForm {
    fn factor_kind(&self) -> AuthFactorKind {
        AuthFactorKind::Totp
    }

    fn form_kind(&self) -> FactorFormKind {
        FactorFormKind::Verify
    }

    fn validate_form(&self) -> Result<&Self, FormError> {
        if self.code.len() != 6 {
            // TODO: Add more complex validation logic for TOTP codes
            Err(FormError::ValidationFailed(
                "TOTP code must be exactly 6 characters.".to_string(),
            ))
        } else {
            Ok(self)
        }
    }

    fn credential(&self) -> Option<&str> {
        Some(&self.code)
    }

    fn fields_map(&self) -> HashMap<String, String> {
        let mut map = HashMap::new();
        map.insert("code".to_string(), self.code.clone());
        if let Some(tenant) = &self.tenant {
            map.insert("tenant".to_string(), tenant.clone());
        }
        if let Some(next) = &self.next {
            map.insert("next".to_string(), next.clone());
        }
        map
    }

    fn verify_against_config(&self, config: &serde_json::Value) -> Result<&Self, FormError> {
        let credential = self.credential().ok_or_else(|| {
            FormError::ValidationFailed("Missing TOTP code credential.".to_string())
        })?;

        if let Some(stored_code) = config.get("code").and_then(|v| v.as_str()) {
            if stored_code == credential {
                Ok(self)
            } else {
                error!("Failed to verify TOTP code versus stored auth config.");
                Err(FormError::ValidationFailed(
                    "Invalid TOTP code.".to_string(),
                ))
            }
        } else {
            Err(FormError::AuthConfigError(AuthFactorKind::Totp.to_string()))
        }
    }
}

/// Form for verifying an OAuth factor.
/// This is used when the user is authenticating via an OAuth provider.
/// It includes the OAuth provider name and an optional redirect URL after verification.
/// The provider is here represented as a string identifier for the OAuth service (e.g., "github", "google", etc.).
/// The actual OAuth flow would typically involve redirecting the user to the provider's login page.
#[derive(Debug, Clone, Deserialize)]
pub struct OauthForm {
    pub provider: String,
    pub tenant: Option<String>,
    pub next: Option<String>,
}

impl FactorForm for OauthForm {
    fn factor_kind(&self) -> AuthFactorKind {
        AuthFactorKind::Oauth
    }

    fn form_kind(&self) -> FactorFormKind {
        FactorFormKind::Verify
    }

    fn validate_form(&self) -> Result<&Self, FormError> {
        if self.provider.is_empty() {
            Err(FormError::ValidationFailed(
                "OAuth provider cannot be empty.".to_string(),
            ))
        } else if self.provider.len() > 64 {
            Err(FormError::ValidationFailed(
                "OAuth provider name must be between 1 and 64 characters.".to_string(),
            ))
        } else {
            Ok(self)
        }
    }

    fn credential(&self) -> Option<&str> {
        Some(&self.provider)
    }

    fn fields_map(&self) -> HashMap<String, String> {
        let mut map = HashMap::new();
        map.insert("provider".to_string(), self.provider.clone());
        if let Some(tenant) = &self.tenant {
            map.insert("tenant".to_string(), tenant.clone());
        }
        if let Some(next) = &self.next {
            map.insert("next".to_string(), next.clone());
        }
        map
    }

    fn verify_against_config(&self, config: &serde_json::Value) -> Result<&Self, FormError> {
        if let Some(stored_provider) = config.get("provider").and_then(|v| v.as_str()) {
            if stored_provider == self.provider {
                Ok(self)
            } else {
                error!("Failed to verify OAuth provider versus stored auth config.");
                Err(FormError::ValidationFailed(
                    "Invalid OAuth provider.".to_string(),
                ))
            }
        } else {
            Err(FormError::AuthConfigError(
                AuthFactorKind::Oauth.to_string(),
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_password_form_validation() {
        let valid = PasswordForm {
            username: "SomeValidUser".to_string(),
            password: "verysecurepassword".to_string(),
            tenant: None,
            next: None,
        };
        assert!(valid.validate_form().is_ok());

        let empty_username = PasswordForm {
            username: "".to_string(),
            password: "verysecurepassword".to_string(),
            tenant: None,
            next: None,
        };

        assert!(empty_username.validate_form().is_err());

        let short_password = PasswordForm {
            username: "user".to_string(),
            password: "short".to_string(),
            tenant: None,
            next: None,
        };
        assert!(short_password.validate_form().is_err());

        let long_password = PasswordForm {
            username: "user".to_string(),
            password: "a".repeat(513),
            tenant: None,
            next: None,
        };
        assert!(long_password.validate_form().is_err());
    }

    #[test]
    fn test_totp_setup_form_validation() {
        let valid = TotpSetupForm {
            secret: "abcd".to_string(), // Now 4 characters, passes validation
            tenant: None,
            next: None,
        };
        assert!(valid.validate_form().is_ok());

        let empty_secret = TotpSetupForm {
            secret: "".to_string(),
            tenant: None,
            next: None,
        };
        assert!(empty_secret.validate_form().is_err());

        let short_secret = TotpSetupForm {
            secret: "abc".to_string(), // Only 3 characters, should fail
            tenant: None,
            next: None,
        };
        assert!(short_secret.validate_form().is_err());
    }

    #[test]
    fn test_totp_verify_form_validation() {
        let valid = TotpVerifyForm {
            code: "123456".to_string(),
            tenant: None,
            next: None,
        };
        assert!(valid.validate_form().is_ok());

        let short_code = TotpVerifyForm {
            code: "12345".to_string(),
            tenant: None,
            next: None,
        };
        assert!(short_code.validate_form().is_err());

        let long_code = TotpVerifyForm {
            code: "1234567".to_string(),
            tenant: None,
            next: None,
        };
        assert!(long_code.validate_form().is_err());
    }
}
